// Auto-generated by scripts/fetch-card-data.js
// NRDB v3 API — cycle/set hierarchy
// Last updated: 2026-03-31

const CARD_SETS = {
  "data_and_destiny": {
    "name": "Data and Destiny",
    "sets": {
      "data_and_destiny": "Data and Destiny"
    }
  },
  "kitara": {
    "name": "Kitara",
    "sets": {
      "the_devil_and_the_dragon": "The Devil and the Dragon",
      "down_the_white_nile": "Down the White Nile",
      "kampala_ascendent": "Kampala Ascendent",
      "council_of_the_crest": "Council of the Crest",
      "sovereign_sight": "Sovereign Sight",
      "whispers_in_nalubaale": "Whispers in Nalubaale"
    }
  },
  "liberation": {
    "name": "Liberation",
    "sets": {
      "the_automata_initiative": "The Automata Initiative",
      "rebellion_without_rehearsal": "Rebellion Without Rehearsal"
    }
  },
  "flashpoint": {
    "name": "Flashpoint",
    "sets": {
      "quorum": "Quorum",
      "blood_money": "Blood Money",
      "escalation": "Escalation",
      "23_seconds": "23 Seconds",
      "martial_law": "Martial Law",
      "intervention": "Intervention"
    }
  },
  "borealis": {
    "name": "Borealis",
    "sets": {
      "parhelion": "Parhelion",
      "midnight_sun": "Midnight Sun"
    }
  },
  "system_update_2021": {
    "name": "System Update 2021",
    "sets": {
      "system_update_2021": "System Update 2021"
    }
  },
  "system_gateway": {
    "name": "System Gateway",
    "sets": {
      "system_gateway": "System Gateway"
    }
  },
  "core_set": {
    "name": "Core Set",
    "sets": {
      "core_set": "Core Set"
    }
  },
  "spin": {
    "name": "Spin",
    "sets": {
      "mala_tempora": "Mala Tempora",
      "true_colors": "True Colors",
      "fear_and_loathing": "Fear and Loathing",
      "second_thoughts": "Second Thoughts",
      "double_time": "Double Time",
      "opening_moves": "Opening Moves"
    }
  },
  "reign_and_reverie": {
    "name": "Reign and Reverie",
    "sets": {
      "reign_and_reverie": "Reign and Reverie"
    }
  },
  "terminal_directive": {
    "name": "Terminal Directive",
    "sets": {
      "terminal_directive_cards": "Terminal Directive Cards",
      "terminal_directive_campaign": "Terminal Directive Campaign"
    }
  },
  "sansan": {
    "name": "SanSan",
    "sets": {
      "the_valley": "The Valley",
      "the_underway": "The Underway",
      "old_hollywood": "Old Hollywood",
      "chrome_city": "Chrome City",
      "the_universe_of_tomorrow": "The Universe of Tomorrow",
      "breaker_bay": "Breaker Bay"
    }
  },
  "red_sand": {
    "name": "Red Sand",
    "sets": {
      "earths_scion": "Earth's Scion",
      "blood_and_water": "Blood and Water",
      "crimson_dust": "Crimson Dust",
      "free_mars": "Free Mars",
      "daedalus_complex": "Daedalus Complex",
      "station_one": "Station One"
    }
  },
  "system_core_2019": {
    "name": "System Core 2019",
    "sets": {
      "system_core_2019": "System Core 2019"
    }
  },
  "mumbad": {
    "name": "Mumbad",
    "sets": {
      "business_first": "Business First",
      "kala_ghoda": "Kala Ghoda",
      "fear_the_masses": "Fear the Masses",
      "democracy_and_dogma": "Democracy and Dogma",
      "salsette_island": "Salsette Island",
      "the_liberated_mind": "The Liberated Mind"
    }
  },
  "ashes": {
    "name": "Ashes",
    "sets": {
      "downfall": "Downfall",
      "uprising": "Uprising"
    }
  },
  "elevation": {
    "name": "Elevation",
    "sets": {
      "elevation": "Elevation"
    }
  },
  "vantage_point": {
    "name": "Vantage Point",
    "sets": {
      "vantage_point": "Vantage Point"
    }
  },
  "honor_and_profit": {
    "name": "Honor and Profit",
    "sets": {
      "honor_and_profit": "Honor and Profit"
    }
  },
  "creation_and_control": {
    "name": "Creation and Control",
    "sets": {
      "creation_and_control": "Creation and Control"
    }
  },
  "revised_core_set": {
    "name": "Revised Core Set",
    "sets": {
      "revised_core_set": "Revised Core Set"
    }
  },
  "genesis": {
    "name": "Genesis",
    "sets": {
      "trace_amount": "Trace Amount",
      "humanitys_shadow": "Humanity's Shadow",
      "a_study_in_static": "A Study in Static",
      "future_proof": "Future Proof",
      "cyber_exodus": "Cyber Exodus",
      "what_lies_ahead": "What Lies Ahead"
    }
  },
  "order_and_chaos": {
    "name": "Order and Chaos",
    "sets": {
      "order_and_chaos": "Order and Chaos"
    }
  },
  "lunar": {
    "name": "Lunar",
    "sets": {
      "up_and_over": "Up and Over",
      "the_source": "The Source",
      "upstalk": "Upstalk",
      "all_that_remains": "All That Remains",
      "first_contact": "First Contact",
      "the_spaces_between": "The Spaces Between"
    }
  },
  "magnum_opus_reprint": {
    "name": "Magnum Opus Reprint",
    "sets": {
      "magnum_opus_reprint": "Magnum Opus Reprint"
    }
  },
  "draft": {
    "name": "Draft",
    "sets": {
      "draft": "Draft"
    }
  },
  "salvaged_memories": {
    "name": "Salvaged Memories",
    "sets": {
      "salvaged_memories": "Salvaged Memories"
    }
  },
  "napd_multiplayer": {
    "name": "NAPD Multiplayer",
    "sets": {
      "napd_multiplayer": "NAPD Multiplayer"
    }
  },
  "magnum_opus": {
    "name": "Magnum Opus",
    "sets": {
      "magnum_opus": "Magnum Opus"
    }
  }
};
